In [24]:
import numpy as np
import pandas as pd

# Memory

In [25]:
df = pd.read_csv("../data/car_evaluation.csv")

In [26]:
df

      vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
...     ...     ...    ...   ...    ...   ...    ...
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [27]:
df.dtypes

vhigh      object
vhigh.1    object
2          object
2.1        object
small      object
low        object
unacc      object
dtype: object

In [28]:
df.memory_usage().sum()

96840

In [29]:
df.memory_usage(deep=True).sum() # deep=True sirve para que se muestre el tamaño real de los datos

728947

In [44]:
import pandas as pd
from math import comb

# Definir los valores posibles de x e y
x_values = range(7)  # 0 a 6 (6 bolas rojas)
y_values = range(6)  # 0 a 5 (5 bolas azules)

# Lista para almacenar los datos
data = []

# Calcular las probabilidades
for x in x_values:
    for y in y_values:
        green_balls = max(0, 2 - (x + y))  # Asegurar que no haya valores negativos
        total_balls = 15
        if green_balls <= 4:
            prob = (comb(6, x) * comb(5, y) * comb(4, green_balls)) / comb(total_balls, 2)
            data.append({"x": x, "y": y, "P(X=x, Y=y)": prob})

# Crear el DataFrame a partir de la lista de datos
df = pd.DataFrame(data)

# Mostrar el DataFrame
df

    x  y  P(X=x, Y=y)
0   0  0     0.057143
1   0  1     0.190476
2   0  2     0.095238
3   0  3     0.095238
4   0  4     0.047619
5   0  5     0.009524
6   1  0     0.228571
7   1  1     0.285714
8   1  2     0.571429
9   1  3     0.571429
10  1  4     0.285714
11  1  5     0.057143
12  2  0     0.142857
13  2  1     0.714286
14  2  2     1.428571
15  2  3     1.428571
16  2  4     0.714286
17  2  5     0.142857
18  3  0     0.190476
19  3  1     0.952381
20  3  2     1.904762
21  3  3     1.904762
22  3  4     0.952381
23  3  5     0.190476
24  4  0     0.142857
25  4  1     0.714286
26  4  2     1.428571
27  4  3     1.428571
28  4  4     0.714286
29  4  5     0.142857
30  5  0     0.057143
31  5  1     0.285714
32  5  2     0.571429
33  5  3     0.571429
34  5  4     0.285714
35  5  5     0.057143
36  6  0     0.009524
37  6  1     0.047619
38  6  2     0.095238
39  6  3     0.095238
40  6  4     0.047619
41  6  5     0.009524

In [31]:
df["P(X=x, Y=y)"].value_counts()

0.057143    4
0.095238    4
0.285714    4
0.571429    4
0.142857    4
0.714286    4
1.428571    4
0.190476    3
0.047619    3
0.009524    3
0.952381    2
1.904762    2
0.228571    1
Name: P(X=x, Y=y), dtype: int64

In [32]:
df.dtypes

x                int64
y                int64
P(X=x, Y=y)    float64
dtype: object

In [33]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Supongamos que df contiene todas las características (x, y) y el target (P(X=x, Y=y))

# Dividir el dataset en entrenamiento y prueba
X = df.drop(columns=["P(X=x, Y=y)"])
y = df["P(X=x, Y=y)"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crear y entrenar el modelo de Random Forest para regresión
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)
rf_regressor.fit(X_train, y_train)

# Hacer predicciones en el conjunto de prueba
y_pred = rf_regressor.predict(X_test)

# Evaluar el modelo
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"MSE: {mse:.4f}")
print(f"R²: {r2:.4f}")

MSE: 0.1020
R²: 0.5038

In [34]:
# RSME
np.sqrt(mse)

0.3193963694476295

In [35]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error


# Separar las características (X e Y) y el target (P(X=x, Y=y))
X = df[['x', 'y']]
y = df['P(X=x, Y=y)']

# Dividir los datos en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crear y entrenar el modelo de regresión lineal
model = LinearRegression()
model.fit(X_train, y_train)

# Hacer predicciones
y_pred = model.predict(X_test)

# Evaluar el modelo
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# RMSE
print(f"Root Mean Squared Error: {np.sqrt(mse)}")

# Mostrar las predicciones
predictions = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})
print(predictions)

Mean Squared Error: 0.2222689481632858
Root Mean Squared Error: 0.47145407853075766
      Actual  Predicted
25  0.714286   0.422317
13  0.714286   0.433651
8   0.571429   0.458338
26  1.428571   0.441337
4   0.047619   0.502045
39  0.095238   0.449022
19  0.952381   0.427984
29  0.142857   0.498396
30  0.057143   0.397630

In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error


# Separar las características (X e Y) y el target (P(X=x, Y=y))
X = df[['x', 'y']]
y = df['P(X=x, Y=y)']

# Dividir los datos en conjunto de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Crear y entrenar el modelo de Random Forest
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Hacer predicciones
y_pred = model.predict(X_test)

# Evaluar el modelo
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")

# RMSE
print(f"Root Mean Squared Error: {np.sqrt(mse)}")

# Mostrar las predicciones
predictions = pd.DataFrame({"Actual": y_test, "Predicted": y_pred})
print(predictions)

Mean Squared Error: 0.10201404081632665
Root Mean Squared Error: 0.3193963694476295
      Actual  Predicted
25  0.714286   0.260952
13  0.714286   0.286095
8   0.571429   0.474667
26  1.428571   1.287143
4   0.047619   0.221429
39  0.095238   0.319524
19  0.952381   0.337619
29  0.142857   0.282286
30  0.057143   0.205524

In [48]:
# porcentaje de error
predictions["Error"] = 100 * (predictions["Actual"] - predictions["Predicted"]) / predictions["Actual"]
print(predictions)

      Actual  Predicted       Error
25  0.714286   0.260952   63.466667
13  0.714286   0.286095   59.946667
8   0.571429   0.474667   16.933333
26  1.428571   1.287143    9.900000
4   0.047619   0.221429 -365.000000
39  0.095238   0.319524 -235.500000
19  0.952381   0.337619   64.550000
29  0.142857   0.282286  -97.600000
30  0.057143   0.205524 -259.666667